spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_DATABASE_USERNAME}
    url: ${MYSQL_DATABASE_URL}
    password: ${MYSQL_DATABASE_PASSWORD}
logging:
  level:
    codesquad.backend:
      issuetracker: info
